### ISSUE TITLE
The XSD import should also include attributes

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#1050]
Currently, only the elements are taken into account during an xsd import.

In an example from DataCite  (https://schema.datacite.org/meta/kernel-4.4/metadata.xsd ) it is shown that attributes play an important role and should therefore also be imported, writable and exportable.

**this results in 3 major task areas.**

- [x] Extension of the import
- [x] Extension of the metadata input
- [x] db update script
- [x] validation
- [ ] #1071

**Comment by DavidBlaa** [comment]
missed database updatescript and validation

**Comment by DavidBlaa** [comment]
export will be implemented in 2.18
