### ISSUE TITLE
Constraints Refactoring 

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#1274]
- [x] #1330
- [x] #1331
- [x] Types: Range, Pattern, Domain
- [x] add Domain List via keyboard
- [x] add Domain List from file 
- [x] #1422
- [x] #1423

## future
- validation after change a constraint
- more api access
- Domain List from Api (external) -> 
- [ ] #1691
- [x] #1421
- [x] #1420

**Comment by geofranzi** [comment]
Example from BioPortal API:
- all children of Organism (http://data.bioontology.org/ontologies/SNOMEDCT/classes/http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNOMEDCT%2F410607006) within the Ontologie SNOMEDCT (https://data.bioontology.org/ontologies/SNOMEDCT) : https://data.bioontology.org/ontologies/SNOMEDCT/classes/http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNOMEDCT%2F410607006/children

**Comment by DavidBlaa** [comment]
![image](https://github.com/BEXIS2/Core/assets/19665289/6e5126c7-8d17-437d-8a88-622e0c4d64db)
