### ISSUE TITLE
Email Header unification

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1308]
see: https://github.com/BEXIS2/Data-curation/discussions/34

all headers current see here: https://github.com/BEXIS2/Core/blob/dev/Components/AAA/BExIS.Security.Services/Utilities/MessageHelper.cs
![image](https://github.com/BEXIS2/Core/assets/15946467/7ea92f11-2636-466e-889f-98fe80621ee3)

"B2 Instance name" - "Entity": "action" (Id: "number")

{entityname} = Dataset / Publication / ...

### Dataset
- [x] BExIS - {entityname}: Created (Id: xxx)
- [x] BExIS - {entityname}: Try to delete (Id: xxx)*
- [x] BExIS - {entityname}: Set public (Id: xxx)
- [x] BExIS - {entityname}: Unset public (Id: xxx)
- [x] BExIS - {entityname}: Purged (Id: {datasetid})
- [x] BExIS - {entityname}: Deleted (Id: xxx)*
- [ ] BExIS - {entityname}: Undeleted (Id: xxx)*
 
### Dataset/Metadata
- [x] BExIS - {entityname}: Metadata updated (Id: xxx)
- [ ] BExIS - Dataset: Metadata completed (Id: xxx) **- not implemented at the moment**

### Dataset/Data structure
-- Should information about the data structure been send?
- [ ] BExIS - Dataset: Data structure created (Id: xxx)
- [ ] BExIS - Dataset: Data structure edited (Id: xxx)
- [ ] BExIS - Dataset: Data structure donwloaded (Id: xxx)

### Dataset/Primary data
-- Is it possible to distinguish between between strutured and unstructured primary data? ( @geofranzi)
-- wirte naming? structured or tabluar; unstructured or file
**--> we can try: tabular / file**
- [ ] BExIS - Dataset: Structured data uploaded (Id: xxx)
- [ ] BExIS - Dataset: Unstructured data uploaded (Id: xxx)

-- Is it possible to distinguish between the initial upload of data, the data update and the appending of data? (@geofranzi)
- [ ] BExIS - Dataset: Structured data updated (Id: xxx)
- [ ] BExIS - Dataset: Structured data appended / added (Id: xxx)
- [ ] BExIS - Dataset: Unstructured data deleted (Id: xxx)

### Dataset/Attachments
- [x] BExIS - Dataset: Attachment uploaded (Id: xxx)
- [x] BExIS - Dataset: Attachment deleted (Id: xxx)
- [ ] BExIS - Dataset: Attachment file xyz downloaded (Id: xxx)

### Dataset/Download
public dataset / internal dataset?
- [ ] BExIS - Dataset: Downloaded (Id: xxx)
-- Is it possible to distinguish between download of complete dataset, only primary data or only metadata? (@geofranzi)
-- Do we want to distinguish between this use cases?
- [ ] BExIS - Dataset: Dataset downloaded (Id: xxx)
- [ ] BExIS - Dataset: Metadata downloaded (Id: xxx)
- [ ] BExIS - Dataset: File xyz downloaded (Id: xxx)

### Units, Dimensions, Datatypes, Meanings, Prefix, External Link, Category, ....

???

### Registration
BExIS - User has registered
BExIS - User tries to register

### Data Requests
Data request from {requester} for dataset with id = {datasetid}
Data request from {requester} for dataset with id = {datasetid} withdrawn
Data request from {requester} for dataset with id = {datasetid} granted
Data request from {requester} for dataset with id = {datasetid} rejected

### Error
Error in System

### Publication - Covered above
- BExIS - Publication: Created (Id: xxx) BExIS
- BExIS - Publication: Metadata updated (Id: xxx)
- BExIS - Publication: File uploaded (Id: xxx)
- BExIS - Publication: File deleted (Id: xxx)
- BExIS - Publication: Downloaded (Id: xxx)
- BExIS - Publication: Purged (Id: xxx)

public dataset / internal dataset?

**Comment by geofranzi** [comment]
New change requests can be done at any time.Some open points also relate to the previous structure.
