### ISSUE TITLE
DB Update Script from 2.18 to 3

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#1366]
# Schema
- [x] Create Schema Diff

# Data

- [x] Update Operations and Features based on added Controllers and Seeddata
- [x] Create EntityTemplates and link them to Datasets
- [x] Convert DataContainer (belong to data structures) To VaraibleTemplate and Variable
- [x] Update Constraints (belong to data container) 

## EntityTemplates
> important is that a entity is only linked to one metadata structure, so this means we need at least one entity Template per used metadata structure 
> after db update script, edit template in ui 
- [x] Create min one EntityTemplate for structured and unstructured
- [x] Structured dummy data entity template per metadata structure

## Data Container - Variable /Template
1. create VariableTemplate based on DataContainer
2. add all informations from data container to each variable
3. link constraints to Variables and VariableTemplates
4. set datacontainer link null (variables & constraints)

- [x] remove data container links from varaibles and templates
- [x] add constraints
- [x] prefix table #1368 
- [x] unit URL #1371
- [x] meaning: add role to ext link #1375
- [x] meaning + constraints table #1372 
- [x] New added columns name crationdate lastlodified and lastmodifieduserref in Constraints Table -> #1431
- [x] New added externalLinkRef to Units Table -> #1371

#837
