### ISSUE TITLE
Release v3.0.0-beta

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1370]
- [x] #1297 
- [x] https://github.com/BEXIS2/Core/issues/1366
- [x] https://github.com/BEXIS2/Core/issues/999
- [x] https://github.com/BEXIS2/Core/issues/965
- [x] release notes
- [x] update B2 website
- [x] demo instance running
- [x] release core & workspace
- [x] info mail
- [x] version update, web.config.sample /settings / database / seeddata
- [x]  update read me
