### ISSUE TITLE
As a Datamanager i want to create a Tag for a version of a dataset

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#1641]
### Acceptance criterias
- [ ] it must be possible to create tags on the version overview page

### Tasks
- [ ] create table of tags in 1:1 releation to version
- [ ] create manager for tags (create, update, delete)
- [ ] create tests for managers
