### ISSUE TITLE
Datasets versions: Creation and Editing 

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1647]
As a user or data manager, I want to create/edit/(delete) versions of my dataset to tag specific versions and hide intermediate editing states of the dataset. 

- Format for versions: 1.0, 2.0 (major); 1.1, 1.2, 2.0 (minor) (created by system based on type)
- it should be possible to give the following additional information:
  - kind of release (minor/major) (if the instance works with both)
  - release note (maybe prefilled with release intention of the user (given when requested release); should be editable (related to #???)
  - release date 
      - minor release = data of request by user 
      - major release = actual date
- sets the show tick in the history table (see #???)

### Acceptance criteria
- [x] It must be possible to create a new version, decide which type, provide notes, and change the date
- [x] It must be possible to change version information

----
### Tasks
- [x] create TagTable to store: 
    - version tag
    - release date
    - current dataset version ID
    - DOI
    - release note/comment (at dataset version)
    - final (boolean)
    - show
- [x] manager for CRUD
- [x] create tests for managers
- [x] edit/create view (permission depend on settings: curated / not curated versions)

**Comment by DavidBlaa** [comment]
![image](https://github.com/BEXIS2/Core/assets/19665289/393b46c0-ead5-4adc-a8d8-4bae91ac03d7)

**Comment by ludmillafigueiredo** [comment]
Related to #1742 , #1743 , #1744.
