### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1892]
# Release 4.0.0
## todos 
- update Skeleton to 3 - not now
- create, update, and link manuals (user + admin) (https://github.com/BEXIS2/Core/issues/2028) - will not be finished -> post 4.0.0
- [x] improve & check help
-  #1837  -> post 4.0.0
-  #1781  -> post 4.0.0
- integrate bexis-ui-tests into pipeline -> post 4.0.0
-  #1604  -> post 4.0.0
- [x] check suggestions (variable)
- [x] check & test new search 
- [x] check & test new primary data view
- [x] check send emails (#1854, ....)
- #1887  -> post 4.0.0
- #390 -> post 4.0.0
- bugs like: 
    - [x] #1870 
    - [x] #1878 
    - [x] #1812
    - #1893
    - [x] #1775
    - [x] #1774
    - [x] #1321

# Release preparation
- [x] release notes
- [x] pipeline success
- [x] update read me
- [x] update version number (db, web.config, general settings)

## code
- [x] run formatter for svelte (lint)
- [ ] run formatter for c# (code maid)

## db update script 
- [x] update version
- [x] seeddata shema.rog and search concept
- [x] search controller
- [x] other new controllers?
- [x] add changes for tags

## merge to
- [x] master
- [x] dev
- [x] workspace
- [x] documents

# release
- [x] core
- [x] workspace
- [x] documents

## attention
- general.settings.json
- ddm.settings.json (tags)
- workspace changed 
- web.config changed

## after release
- [x] update demo
update UI project libraries
update nuget packages
update jenkins
- [x] send mail
- [ ] update website
