### ISSUE TITLE
Replace primary data Telerik Table

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#747]
several problems could be solved:
#744 
#730 
#641 
sorting sometimes not possible
not all missing values can be substituted correctly (date)

- [x] function to return JSON with already replaced missing values (do it clientside)
- [x] provide all needed functions for server-side paging, filtering, sorting required by datatables (https://datatables.net/manual/server-side)
- [x] decide where / what to search / filter should be possible
- [x] #641 
- [x] create a view to use a data in the new table
