### ISSUE TITLE
File Upload and Display: Refactoring

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#818]
- [x] Revise file storgage / moving during upload types
- [x] Refactore backend functions
- [x] #845
----
- [x] Add description to each uploaded file
- [x] Add settings to make description mandatory
- [x] #846
----
- [x] Add setting for allowed file types (whitelist) (set by the tenants)
- [x] Add setting to restrict file size
- [x] Add setting to restrict the number of multiple files (postponed)
----
- [x] Replace for structured / unstructured upload
- [x] Replace for Attachments
---- 
- [x] Add description to structured and attachment view
- [x] Allow change of description  -> MMM / Attachment View

**Comment by DavidBlaa** [comment]
-> **withlist** is defined in the tenants and its loaded from there
