### ISSUE TITLE
Primary Data: Validation

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#821]
Validation should run as an independent step. To remember if validation runs successfully / or with errors, the result needs to be stored and accessible for the final import step.

- [x] run as independent step
- [x] seperate file reader info selection view from suggestion, and use it when validation failed
- [x] save & store result (e.g. as hash based on: file name + size + date  & col name, order, data type)
- [x] save start/end header and data area in file (refer to: file name + size + date )
- [x] use result for finale import
---
- [x] maybe check primary keys and store at close to data structure
- [x] implement Check to set Status in Hook
- [x] #861

more infos :
https://miro.com/app/board/o9J_lfsbYyk=/?moveToWidget=3458764514439654797&cot=14

**open issues**

- [x] #537
- [x] #254
