### ISSUE TITLE
Dataset: Add status

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#822]
During the life cycle of a dataset, it may have different stages, especially in curated instances. After creation the dataset is probably in "draft" stage, during curation in "under revision" and finally the data curator would like to set it to "approved".

The status should also trigger if a dataset is findable in the search.

- [ ] add column for status
- [ ] add setting for status (user defined status + index:yes/no)
- [ ] change add to index function (check status and "yes/no", if status is set)
- [ ] add edit to manage datasets
- [ ] show status
---
- [ ] visibility in Dashboard/My data ?
---
Wishlist from BE:
- [ ] instances defined keywords as array attached to dataset (e.g. public, centralData, project x, ...) to show to a user under MyData (Background: indicate why rights are given -> maybe other solution better)
