### ISSUE TITLE
Data structure: Create from file

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#824]
- [x] UI select type of creation 
- [x] select file from uploaded files (depends on #818)
-  ~~allow to choose EXCEL or CSV.~~ (move to next release )->  #843
- [x] detect used delimiter and read file
- [x] #850
   - check current lib or use https://datatables.net/extensions/select/
   - show default missing value(s) (allow to delete, add new)
   -  show first 100 lines, allow to show more
   - ask, if shown correct (-> change delimiter)
   - select data area? 
   - save result as JSON for later  (useable for validation and submission)
- [x] data type detection 
   - max 100 random (not as block!)
   - consider missing values
- [x] try to match unit
- [x] (try to match template)
- [x] UI to check and edit result (see Miro)
- [x] Save (see #847 )
------
- [x] Deprecate Easy Upload Workflow
