### ISSUE TITLE
Redesign of Entity Edit View

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#829]
# Backend
- [x] #830
- [x] #834
- [x] Extension of the module settings with hooks and views
- [x] #844

## Hooks
- [x] #835
- [x] #836
- [x] create hooks in RPM
- [x] #839
- [x] #840
- [x] add all hook places in the storiebook

# Frontend
- [x] Separate view and edit entity view

## DCM - Edit
- [x] Refactor Edit view by loading hooks
- [x] Enhance View by loading views

## DDM - View
- [x] #857

## svelte-bexis2-dcm-ui
- [x] create a dcm svelte module repo
- [x]  enhance workspace 
- [x] prepare dcm module to be able to load the svelte views

## refactor ui

> https://miro.com/app/board/o9J_lfsbYyk=/?moveToWidget=3458764515545158740&cot=14

- [x] planning

**Comment by DavidBlaa** [comment]
opened again because of a new concept
