### ISSUE TITLE
Refactoring Variable Concept - DB

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#837]
- [x] conceptual design
- [x] break into sub tasks
- [x] #842
- [x] change access for data type
- [x] update script to move data type
- [x] create list for date patterns
- [x] update script to move date patterns
- [x] change access for date pattern
- [x] change access for constraints
- [x] update script for constraints
--- 
**can be done later:**
- [x] Meaning/Category & Variable Templates
