### ISSUE TITLE
Change DB structure for variables

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#842]
- [x] add data type to variable
- [x] add date pattern to variable
---------
- [x] create variable constraints container
- [x] add variable constraint container to variable
-------
- [x] #854
- [x] add meaning/category to variable (0 - n)
-----
- [x] create new variable template
---
- [x] add comments in code
- [x] transformation SQL
