### ISSUE TITLE
Refactoring Variable Concept - Core & UI (Part 1: Data structure & Variables)

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#847]
- [x] data structure :allow for none  (allow for change? ..still necessary with new concept?)
- [x] Refactoring create data structure (without file)
    - with/without template
    - provide(var templates, units, date patterns, data types via API calls (for UI), (Meaning/Category -> Part 2)
    - allow for add at position (not at end)(Wish from Cornelia)
- [x] Adjust / check existing functions e.g.: Copy data structure, Edit and Delete
- [x] Create data structure based on the result of new workflow "upload from file"
   -  (interim? and finally save)
   - error handling
   - check rules...
   - decide where to store primary keys
- [x] Adjust data structures list view
- [x] Adjust dataset variable view  
   - allow for change
