### ISSUE TITLE
Refactoring Variable Concept - Core & UI (Part 2: Meaning/Categories & Links)

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#848]
- [x] add structure to DB (#837 )
  - Variable to Meaning/Categories: 0 to n
  - Poly-hierarchy Meaning/Categories
  - Links to Meaning/Categories: 0 to n
  - Links to Variable? 0 to n
  - migration from former Variable Templates
 - [x] Change Meaningsmanager functions to classes  (#1338 )
 - [x] Add function to create new External links on the fly while creating new meaning (#1340 )
 
User friendly UI for Curators: 
 - [x] View 
 - [x] Create & Edit Meaning/Categories
 - [x] Create & Edit Link
 - [x] Add Links (future provide search in GFBio Terminology Service)  
- [x] add meanings to variables
- [x] add meanings to varaible templates
- [x] copy meanings from template to variable

# extra
- [x] #1368 
- [x] #1375
- [x] #1372
- [x] enhance external links with prefix in ui
- [x] set required meanings via settings
- [x] after selection of meaning by variables, show the description and  may existing links in the information area
