### ISSUE TITLE
Versioning: visibility and accessibility on public and internal datasets

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#853]
### Problem

- **Szenario 1**: Draft and interim versions (Metadata) - hide on public access 
- **Szenario 2**: Citation - refer to an (actively by curators or by users ) proofed and named state (version/release) instead of the version id
- **Szenario 3**: DOI - refer to linked version + minor revisions until the 1st data/file change
- **Szenario 4**: Time series datasets - make only parts of the versions public 

### Visibility for logged-in user 
- **Szenario 1** Lastest version -> same as for not-logged in users (Setting: restrict_latest_version_logged_in: true)
- **Szenario 2** Latest version -> real latest (could be a newer non-public version (Setting: restrict_latest_version_logged_in: false (default))
- **Szenario 3** Show reduced list of versions (like for not-logged in user), if no edit permissions (Settings: reduce_versions_select_logged_in: true (default))
- **Szenario 4** Full list (reduce_versions_select_logged_in: false )

### Possible solution
_without permission restrictions on public access_
- dataset version table: add column for major version / release + column for description (-> 1, 2)
- public datasets view: reduce the dropdown list to all major version (instance setting or only if at least one exist)(-> 1)
- access via URL: if at least one major version exists, forward until the next data/file version starting from URL version ID (-> 3) (Would require an option to enforce NO forward! and more details on top)

_with permission restriction on public access_
- dataset version: add public access status, copy status for metadata changes, do not copy for data changes (-->4)(when and who can set, always set or only if needed?)

**--> no permission management on version level! (only restriction for public access yes/no)**

### Implementation steps
- [x] add fields to the data versions table
- [x] change dropdown list logic
- [x] add extra check for public datasets 
- [x] add forwarding + change information on top 
- [x] add prevent forwarding (may be needed for dataset links and/or to go back to the original associated version with DOI)
- [x] add settings
# moved to 2.15 (#936 )
- add function to set major version + add text (where?)
- add state(s) of version + visual hint for new data changes to manage dataset page for data curators

**Comment by geofranzi** [comment]
Add date for public access for #893
