### ISSUE TITLE
Entity Links

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#880]
Backend requirements:
- [ ] Authentification via token
- [ ] Set CORS to * / enable preflight
- [ ] REST calls for creation and related get function
- [ ] REST calls for editing one link
- [ ] REST calls for viewing all links related to one dataset id

Creation of Entity Links
- [ ] Edit form to create new links

Curation & Editing
- [ ] Curation page to show and change difference to most recent version #874
- [ ] Add function to edit links (for curator and user?)  #752

List view and Visualisation of relationships
- [ ] simple list view
- [ ] visualization showing the different link types
