### ISSUE TITLE
Extension of BEXIS2 by the concept of the entity template

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#896]
Entity templates are a collection of rules and predefined values to create a dataset for a topic.

**more informations** : 
https://miro.com/app/board/o9J_lfsbYyk=/?moveToWidget=3458764517203172010&cot=14

ToDos

## Backend
- [x] Create Entity of EntityTemplate
- [x] Create nHibernate Mapping file of EntityTemplate
- [x] Create Manager to create and update a EntityTemplate
- [x] Create EntityTemplate Controller
- [x]  Unit Tests for the Manager

## Frontend
- [x] Overview over all existing EntityTemplates
- [x] Create a form to create and update the entity template
- [x] Create a Selection View
- [x] Change the entry in the menu
