### ISSUE TITLE
Refactoring Dataset Details View

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#907]
The refactoring will take place step-wise by removing tabs and replacing them with inline components on one page. Eg. . First, what will change is the displaying of metadata.

## List of items/components to consider
- [x] Title/Citation
- [x] Id
- [x] Version
- [x] Version selection (selection list (now), semantic display grouping/hiding, ...)
- [x] Citation
- [x] DOI (from metadata or table?)
- [x] Links #880 
- [x] Metadata view
  - display of item lists
- [x] Navigation
- [x] ~~Permissions~~ -> Dataset Edit View
- [x] Data structure
- [x] Primary data (structured/unstructured)
- [ ] Map (?)
- [x] Download Button 
- [x] Edit Button
- [x] Attachments
- Data viz
- Data/Metadata quality
- Info box (incomplete metadata)
- Status
- Public 

## Layout ideas
FZ: 
- one page; trigger load content while scrolling the page (-> do not load primary data or viz, if no one scrolls below metadata)
- left navigation: Metadata, Links, Data, Data viz/stat, Modul1, Module2, ... -> all with sub-items - open based on the viewport (?)
- data: enhanced header with most of the info from data structure on expand 
- data structure: display on demand separate and/or detailed as a tooltip to the data table header?
- also a nice way to show variables details: https://search.dataone.org/view/doi%3A10.18739%2FA2JH3D41P#urn%3Auuid%3A73800a2e-7617-470a-83aa-b530a01f32e3

# Download
- [ ] restrict zip Download to max size

**Comment by geofranzi** [comment]
**Please do not change the first comment!**

Please add use cases and wishes as comments. You can also add images to illustrate. Please always add also the project(s) which could be interested in the new design and/or feature.

**Comment by geofranzi** [comment]
**Please do not change the first comment!**

Please add use cases and wishes as comments. You can also add images to illustrate. Please always add also the project(s) which could be interested in the new design and/or feature.

We are interested in use cases that like 
- to present/show certain elements in a specific way
- to show dataset links
- to show primary data/quality parameter
- to integrate own modules
- ..

We are interested in UI ideas how to structure the metadata.
-
