### ISSUE TITLE
Primary Data: Validation & Linking

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#908]
- [ ] Validation against Datasets
- [ ] Linking primary data to other Datasets (?)
- [ ]  Collect ideas / constraints / problems

Projects which showed interest: BE, NFDI (bayrischer Wald), MV, AD, BioDivBank
