### ISSUE TITLE
New API: Metadata structure 

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#916]
We need to provide a metadata structure via API call for the metadata quality checks and (external) metadata entry.
In addition to the current mapping info, it would be good to have:

# Json Schema
- [x] #953

# Json
- [x] Convert Metadata to Json
- [x] extending the metadata api to get metadata in json as well
- [x] Write tests to cover borderline cases and happy paths cases

# Json -> Metadata
- [x] Convert json to metadata
- [x] #956
- [x] unit tests

**Comment by sventhiel** [comment]
- [ ] test
