### ISSUE TITLE
 Darwin Core Export

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#917]
Implementation plan for BEXIS2 Darwin Core Export:
### Phase 1 – Export / Download

**Resource Metadata**
- [x] #958
- [x] #963
- [x] #1092
- [x] #1083
- [x] #1093
- [x] validate mapping between concept and metadata structure
- [x] write a converter from concept to metadata eml for the dwc 

**Meta - BEXIS2v2**
- [x] create manuel workflow for mapping dwc terms to structure variables (https://dwc.tdwg.org/terms/)
- [x] create Model for meta file and create serialization
- [x] generate metadata file based on the primary data file and the dwc terms 

**Meta - BEXIS2v3**
- [x] #1574
- [x] Add settings variables to add / change / maintain fixed values for export
- [x] Create a user workflow to ask the user interactively during the creation of missing items (like type of dataset)

**Data**
- [x] use the existing function to collect the data of a dataset and stored in the dwc folder
- [x] use csv export
- [x] add id to each row

**Converter**
- [x] add datarepo und broker for gfbio
- [x] add converter for gfbio
- [x] add metadata export function to converter
- [x] add meta file to converter
- [x] add primary data to converter 

**DWC zip**
- [x] configer a folder place where all dwc package are stored for the datasets
- [x] Create a download package

**Enhancements**
- [x] mapping ui need indicator, how many mappings are needed
- [x] #1104

### Phase 2 – Automatic Transfer (not investigated yet)
