### ISSUE TITLE
Redesign of the entity linking page

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#957]
> The current entity link page is to be revised. 
![Image](https://user-images.githubusercontent.com/19665289/185107377-f8c36f3d-6d3b-4140-9ce8-17e94f71e434.png)

The aim is to make the user interface clearer and more user-friendly.
Therefore, we would like to create a user experience design and user interface design.
Furthermore, the new site should be programmed in Svelte.

- [ ] Collecting use cases
- [ ] Creation of a user experience design for the area of entity linking
- [ ] Creation of a user Interface design for the area of entity linking
- [ ] Development of necessary backend functions
- [ ] Development of the site in Svelte
