### ISSUE TITLE
SAM Refactoring to Svelte

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/Core#997]
Refactoring of existing SAM views to Svelte including a few improvements and new views from a different point based on already implemented functions. 

- [ ] #813
- [ ] #794
- [ ] #715 
- [x] #65 
- [x] #54

### Backend (APIs)
- [x] #1174
- [x] #1689
- [ ] view: Former Members
- [x] #1173
- [x] #1212
- [ ] view & CRUD Feature Permissions
- [ ] view & CRUD Entity Permissions
- [ ] view: & Edit Manage Datasets
- [ ] new admin view: "my data" view for each user, view of groups/direct permissions
- [ ] #1785
### Frontend (Svelte)
- [x] #1690
- [ ] view & edit Former Members
- [x] #1202
- [ ] CRUD Groups
- [ ] view&edit: Feature Permissions
- [ ] view&edit: Entity Permissions
- [ ] view: Manage Datasets
- [ ] new admin view: "my data" view for each user, view of groups/direct permissions

**Comment by geofranzi** [comment]
Requested by BE:
Add indicator if a user belongs to any group or not (yes/no) -> color coding users in UI?
